/*
 * This Java source file was generated by the Gradle 'init' task.
 */
import org.junit.Test;
import static org.junit.Assert.*;

public class LibraryTest {
    @Test public void testFibonacci() {
        Library classUnderTest = new Library();
        assertEquals(55, classUnderTest.fib(10));
    }
}
